# Production environment overrides
version: '3.8'

services:
  recharge-mcp-server:
    restart: always
    environment:
      - NODE_ENV=production
      - DEBUG=false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M